services:
  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend-network

  lot-service:
    ports:
      - "8081:8081"
    build:
      context: .
      dockerfile: ./lot-service/Dockerfile
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_started
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge